import {checkStorage} from "../utils/utils";

/**
 * Демо карты
 * @type {array}
 */
const demoCharts =
  [
    {
      name: 'chart-Demo chart 1',
      data: {
        atma: {index: 105,
          house: 8,
          sign: 12,
          nakshatra: 27,
          pada: 106},
        atmadara: {index: -1,
          house: -1,
          sign: -1,
          nakshatra: -1,
          pada: -1},
        buddha: {index: 62,
          house: 3,
          sign: 7,
          nakshatra: 16,
          pada: 63},
        chandra: {index: 47,
          house: 2,
          sign: 6,
          nakshatra: 12,
          pada: 48},
        dara: {index: 19,
          house: 11,
          sign: 3,
          nakshatra: 5,
          pada: 20},
        daraatma: {index: -1,
          house: -1,
          sign: -1,
          nakshatra: -1,
          pada: -1},
        guru: {index: 29,
          house: 12,
          sign: 4,
          nakshatra: 8,
          pada: 30},
        ketu: {index: 0,
          house: 9,
          sign: 1,
          nakshatra: 1,
          pada: 1},
        lagna: {index: 6,
          house: 1,
          sign: 1,
          nakshatra: 2,
          pada: 7},
        lagnesha: {index: -1,
          house: -1,
          sign: -1,
          nakshatra: -1,
          pada: -1},
        mangala: {index: 51,
          house: 2,
          sign: 6,
          nakshatra: 13,
          pada: 52},
        rahu: {index: 45,
          house: 2,
          sign: 6,
          nakshatra: 12,
          pada: 46},
        surya: {index: 43,
          house: 1,
          sign: 5,
          nakshatra: 11,
          pada: 44},
        zani: {index: 81,
          house: 6,
          sign: 10,
          nakshatra: 21,
          pada: 82},
        zukra: {index: 44,
          house: 1,
          sign: 5,
          nakshatra: 12,
          pada: 45},
      },
    },
    {
      name: 'chart-Demo chart 2',
      data: {atma: {index: 1,
        house: 12,
        sign: 1,
        nakshatra: 1,
        pada: 2},
      atmadara: {index: -1,
        house: -1,
        sign: -1,
        nakshatra: -1,
        pada: -1},
      buddha: {index: 62,
        house: 3,
        sign: 7,
        nakshatra: 16,
        pada: 63},
      chandra: {index: 47,
        house: 2,
        sign: 6,
        nakshatra: 12,
        pada: 48},
      dara: {index: 32,
        house: 3,
        sign: 4,
        nakshatra: 9,
        pada: 33},
      daraatma: {index: -1,
        house: -1,
        sign: -1,
        nakshatra: -1,
        pada: -1},
      guru: {index: 52,
        house: 2,
        sign: 6,
        nakshatra: 14,
        pada: 53},
      ketu: {index: 55,
        house: 3,
        sign: 7,
        nakshatra: 14,
        pada: 56},
      lagna: {index: 15,
        house: 1,
        sign: 2,
        nakshatra: 4,
        pada: 16},
      lagnesha: {index: -1,
        house: -1,
        sign: -1,
        nakshatra: -1,
        pada: -1},
      mangala: {index: 51,
        house: 2,
        sign: 6,
        nakshatra: 13,
        pada: 52},
      rahu: {index: 53,
        house: 2,
        sign: 6,
        nakshatra: 14,
        pada: 54},
      surya: {index: 43,
        house: 1,
        sign: 5,
        nakshatra: 11,
        pada: 44},
      zani: {index: 61,
        house: 3,
        sign: 7,
        nakshatra: 16,
        pada: 62},
      zukra: {index: 58,
        house: 3,
        sign: 7,
        nakshatra: 15,
        pada: 59}},
    },
  ];

/**
 * @property {function} createDemoCharts -
 * Добавляет в LocalStorage демо карты
 * @return {void}
 */
export function createDemoCharts() {
  demoCharts.forEach((obj) => {
    checkStorage(
        obj.name,
        obj.data
    );
  });
}
