import {checkStorage} from "../utils/utils";

/**
 * @type {Array} demoCharts - Объект с данными карт
 */
const demoCharts =
  [
    {
      name: 'chart-Demo chart 1',
      data: {
        atma: {index: 32,
          house: -1,
          sign: 4,
          nakshatra: 9,
          pada: 33},
        atmadara: {index: -1,
          house: -1,
          sign: -1,
          nakshatra: -1,
          pada: -1},
        buddha: {index: 62,
          house: 3,
          sign: 7,
          nakshatra: 16,
          pada: 63},
        chandra: {index: 47,
          house: 2,
          sign: 6,
          nakshatra: 12,
          pada: 48},
        dara: {index: 50,
          house: -1,
          sign: 6,
          nakshatra: 13,
          pada: 51},
        daraatma: {index: -1,
          house: -1,
          sign: -1,
          nakshatra: -1,
          pada: -1},
        guru: {index: 52,
          house: 2,
          sign: 6,
          nakshatra: 14,
          pada: 53},
        ketu: {index: 55,
          house: 3,
          sign: 7,
          nakshatra: 14,
          pada: 56},
        lagna: {index: 44,
          house: 1,
          sign: 5,
          nakshatra: 12,
          pada: 45},
        lagnesha: {index: -1,
          house: -1,
          sign: -1,
          nakshatra: -1,
          pada: -1},
        mangala: {index: 51,
          house: 2,
          sign: 6,
          nakshatra: 13,
          pada: 52},
        rahu: {index: 53,
          house: 2,
          sign: 6,
          nakshatra: 14,
          pada: 54},
        surya: {index: 43,
          house: 1,
          sign: 5,
          nakshatra: 11,
          pada: 44},
        zani: {index: 61,
          house: 3,
          sign: 7,
          nakshatra: 16,
          pada: 62},
        zukra: {index: 58,
          house: 3,
          sign: 7,
          nakshatra: 15,
          pada: 59},
      },
    },
    {
      name: 'chart-Demo chart 2',
      data: {
        atma: {index: 32,
          house: -1,
          sign: 4,
          nakshatra: 9,
          pada: 33},
        atmadara: {index: -1,
          house: -1,
          sign: -1,
          nakshatra: -1,
          pada: -1},
        buddha: {index: 62,
          house: 3,
          sign: 7,
          nakshatra: 16,
          pada: 63},
        chandra: {index: 47,
          house: 2,
          sign: 6,
          nakshatra: 12,
          pada: 48},
        dara: {index: 50,
          house: -1,
          sign: 6,
          nakshatra: 13,
          pada: 51},
        daraatma: {index: -1,
          house: -1,
          sign: -1,
          nakshatra: -1,
          pada: -1},
        guru: {index: 52,
          house: 2,
          sign: 6,
          nakshatra: 14,
          pada: 53},
        ketu: {index: 55,
          house: 3,
          sign: 7,
          nakshatra: 14,
          pada: 56},
        lagna: {index: 44,
          house: 1,
          sign: 5,
          nakshatra: 12,
          pada: 45},
        lagnesha: {index: -1,
          house: -1,
          sign: -1,
          nakshatra: -1,
          pada: -1},
        mangala: {index: 51,
          house: 2,
          sign: 6,
          nakshatra: 13,
          pada: 52},
        rahu: {index: 53,
          house: 2,
          sign: 6,
          nakshatra: 14,
          pada: 54},
        surya: {index: 43,
          house: 1,
          sign: 5,
          nakshatra: 11,
          pada: 44},
        zani: {index: 61,
          house: 3,
          sign: 7,
          nakshatra: 16,
          pada: 62},
        zukra: {index: 58,
          house: 3,
          sign: 7,
          nakshatra: 15,
          pada: 59},
      },
    },
  ];

/**
 * @property {Function} createDemoCharts -
 * Добавляет в LocalStorage демо карты
 * @return {void}
 */
export function createDemoCharts() {
  demoCharts.forEach((obj) => {
    checkStorage(
        obj.name,
        obj.data
    );
  });
}
